version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: yarvan-postgres
    environment:
      POSTGRES_DB: yarvan_db
      POSTGRES_USER: yarvan
      POSTGRES_PASSWORD: yarvan123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: yarvan-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: